# Generated by Django 2.2.4 on 2024-01-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='updated_at',
        ),
    ]
